rss: /atom.xml

# 是否开启访问量统计功能(不蒜子)
busuanzi:
    enable: true

# offline config passed to sw-precache.
service_worker:
    maximumFileSizeToCacheInBytes: 5242880
    staticFileGlobs:
        - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
    stripPrefix: public
    verbose: true

# Code beautify
all_minifier: true

# word count
word_count: true

# Extensions
## Plugins: http://hexo.io/plugins/
# RSS订阅
plugin:
    - hexo-generator-feed
#Feed Atom
feed:
type: atom
path: atom.xml
limit: 20

markdown:
    preset: "default"
    render:
        html: true
        xhtmlOut: false
        langPrefix: "language-"
        breaks: false
        linkify: true
        typographer: true
        quotes: "“”‘’"
    enable_rules:
    disable_rules:
    plugins:
        - markdown-it-abbr
        - markdown-it-cjk-breaks
        - markdown-it-container
        - markdown-it-deflist
        - markdown-it-emoji
        - markdown-it-footnote
        - markdown-it-ins
        - markdown-it-mark
        - markdown-it-sub
        - markdown-it-sup
    anchors:
        level: 2
        collisionSuffix: ""
        permalink: false
        permalinkClass: "header-anchor"
        permalinkSide: "left"
        permalinkSymbol: "¶"
        case: 0
        separator: "-"

search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

