
# Code Highlight theme
# Available value:
#    normal | night | night yilia | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
# night yilia - https://github.com/litten/hexo-theme-yilia
highlight_theme: normal

rss: /atom.xml

# 是否开启访问量统计功能(不蒜子)
busuanzi:
 enable: true